# Site settings
title: Antonio Molner Domenech
description: My personal portfolio
url: http://www.antoniomolner.com

# User settings
username: Antonio Molner Domenech
user_description: I am a Computer Science Degree student and enthusiastic app developer. I started to learn programming when I was a teenager. Since then I have never stop to learn new things and to accept new challenges. I have worked in several personal and professional projects using different technologies, such as Augmented Reality or Geospatial data. Recently I started to learn Google Tango and AR technologies to boost my career.
user_title: Software Developer
email: me@antoniomolner.com
twitter_username: antonio_molner
github_username:  antoniomdk

twitter:
  username: antonio_molner

author: Antonio Molner Domenech

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

gems:
  - jekyll-seo-tag